# name: kubia-multiport-svc.yaml
# author:  Satish Srinivasan
# version: 1.0
# since:   2022-04-03

# a yaml descriptor to create a simple service with multiple ports.
# Two ports here. 80(portname http) mapped to internal port 8080 and
# 443(portname https) mapped to internal port 8443

apiVersion: v1
kind: Service
metadata: 
  name: kubia-multi-port
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: kubia
