# name: kubia-svc.yaml
# author:  Satish Srinivasan
# version: 1.0
# since:   2022-03-31

# a yaml descriptor to create a simple service.

apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubia
