# name: kubia-rc.yaml
# author:  Satish Srinivasan
# version: 1.0
# since:   2022-03-23

# a simple yaml descriptor for creating a Replication Controller with replica count 3

apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
