# name: cronjob.yaml
# author:  Satish Srinivasan
# version: 1.0
# since:   2022-03-27

# this yaml descriptor creates a simple 'cronjob' to be run every 15 mins

apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job-every-fifteen-minutes
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: luksa/batch-job
