# name: kubia-svc-nodeport.yaml
# author:  Satish Srinivasan
# version: 1.0
# since:   2022-04-19

# This yaml descriptor creates a kubernetes service of type NodePort. This service is exposed through the port 80 
# when accessed through internal Cluster IP (which can be accessed only internally from inside the kubernetes cluster#)
# And also each Kubernetes node in the cluster exposes this service through the port 30123(which is called NodePort)
# . Through this NodeIp:nodePort combination, this service can be accessed by external clients 
# also(ofcourse, firewall for the port 30123 must be opened for Ingress traffic into each of these Kubernetes Nodes)
# Note: Please note that accessing this service externally using the above mentioned approach has a problem since if
# the particular kubernetes node, which is being used to access the service, goes down, then this service becomes 
# inaccessible for the external client. To solve this problem, we need to create Kubernetes Service of type 
# LoadBalancer which can redirect to an alternate/active node if a particular node fails/goes down.

apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30123
  selector:
    app: kubia
