# name: kubia-manual.yaml
# author:  Satish Srinivasan
# version: 1.0
# since:   2022-03-21
apiVersion: v1
kind: Pod
metadata:
   name: kubia-manual
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
